import { Component, OnInit } from '@angular/core';
import { AsyncLocalStorage } from 'angular-async-local-storage';
import { Router } from '@angular/router';
import {PopoverModule} from "ng2-popover";

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  data = [
    {
      "id": "SCQGLR1086E02.g",
      "description": "endo-beta- -glucanase precursor",
      "sequence": "XAQQLFEFGDRYRGTYDSSIAEVRSYYASVSGYQDELLWAALWLHRATGRDDYLRYAVDKAESFGGVGWAMTEFSWDVKYAGVQVLAAKLLLEGDPGALKHRSVLEQYKAKAEHYLCACLGRNGGNGSDNVERSPGGMLYVRQWNNLQYVXQRRX"
    },
    {
      "id": "SCQGLR1086E02.g",
      "description": "endo-beta- -glucanase precursor",
      "sequence": "XAQQLFEFGDRYRGTYDSSIAEVRSYYASVSGYQDELLWAALWLHRATGRDDYLRYAVDKAESFGGVGWAMTEFSWDVKYAGVQVLAAKLLLEGDPGALKHRSVLEQYKAKAEHYLCACLGRNGGNGSDNVERSPGGMLYVRQWNNLQYVXQRRX"
    },
    {
      "id": "SCQGLR1086E02.g",
      "description": "endo-beta- -glucanase precursor",
      "sequence": "XAQQLFEFGDRYRGTYDSSIAEVRSYYASVSGYQDELLWAALWLHRATGRDDYLRYAVDKAESFGGVGWAMTEFSWDVKYAGVQVLAAKLLLEGDPGALKHRSVLEQYKAKAEHYLCACLGRNGGNGSDNVERSPGGMLYVRQWNNLQYVXQRRX"
    },
    {
      "id": "SCQGLR1086E02.g",
      "description": "endo-beta- -glucanase precursor",
      "sequence": "XAQQLFEFGDRYRGTYDSSIAEVRSYYASVSGYQDELLWAALWLHRATGRDDYLRYAVDKAESFGGVGWAMTEFSWDVKYAGVQVLAAKLLLEGDPGALKHRSVLEQYKAKAEHYLCACLGRNGGNGSDNVERSPGGMLYVRQWNNLQYVXQRRX"
    },
    {
      "id": "SCQGLR1086E02.g",
      "description": "endo-beta- -glucanase precursor",
      "sequence": "XAQQLFEFGDRYRGTYDSSIAEVRSYYASVSGYQDELLWAALWLHRATGRDDYLRYAVDKAESFGGVGWAMTEFSWDVKYAGVQVLAAKLLLEGDPGALKHRSVLEQYKAKAEHYLCACLGRNGGNGSDNVERSPGGMLYVRQWNNLQYVXQRRX"
    },
    {
      "id": "SCQGLR1086E02.g",
      "description": "endo-beta- -glucanase precursor",
      "sequence": "XAQQLFEFGDRYRGTYDSSIAEVRSYYASVSGYQDELLWAALWLHRATGRDDYLRYAVDKAESFGGVGWAMTEFSWDVKYAGVQVLAAKLLLEGDPGALKHRSVLEQYKAKAEHYLCACLGRNGGNGSDNVERSPGGMLYVRQWNNLQYVXQRRX"
    },
    {
      "id": "SCQGLR1086E02.g",
      "description": "endo-beta- -glucanase precursor",
      "sequence": "XAQQLFEFGDRYRGTYDSSIAEVRSYYASVSGYQDELLWAALWLHRATGRDDYLRYAVDKAESFGGVGWAMTEFSWDVKYAGVQVLAAKLLLEGDPGALKHRSVLEQYKAKAEHYLCACLGRNGGNGSDNVERSPGGMLYVRQWNNLQYVXQRRX"
    }];
 
  ngOnInit() {
    
  }

}
